// KIIP so'z bilimi — to'rtta mavzuviy to'plam.
// Har bir so'zda: ko (koreyscha), uz (o'zbekcha ma'no).
window.VOCAB_SETS = [
  {
    id:"v1",
    title:"감정·성격 형용사 (Hissiyot & xarakter)",
    words:[
      {ko:"뿌듯하다",      uz:"O'zidan mamnun, g'ururlanish hissi"},
      {ko:"섭섭하다",      uz:"Xafa, achindi (kimdir ketganda yoki kutilgan bo'lmasa)"},
      {ko:"억울하다",      uz:"Adolatsizlikdan g'azablanmoq, bejizga ayblanmoq"},
      {ko:"허탈하다",      uz:"Kuch-quvvatsiz, umid puchga chiqishi"},
      {ko:"답답하다",      uz:"Tiqilinch hissi, o'zini ifodalay olmaslik"},
      {ko:"아쉽다",        uz:"Afsuslantiruvchi, to'liq emas degan his"},
      {ko:"성실하다",      uz:"Vijdonli, ishonchli, mas'uliyatli"},
      {ko:"꼼꼼하다",      uz:"Puxta, e'tiborli, batafsil ishlaydigan"},
      {ko:"부지런하다",    uz:"Tirishqoq, mehnatkash, harakatchan"},
      {ko:"나태하다",      uz:"Yalqov, dangasa, ishdan bo'yin tovlaydigan"},
      {ko:"내성적이다",    uz:"Odamovi, ichki dunyo odami (introvert)"},
      {ko:"외향적이다",    uz:"Muloqotchan, odamsevar (extrovert)"},
      {ko:"적극적이다",    uz:"Faol, tashabbus bilan ish yurituvchi"},
      {ko:"소극적이다",    uz:"Passiv, sust, tashabbus ko'rsatmaydigan"},
      {ko:"긍정적이다",    uz:"Optimistik, ijobiy fikrlaydigan"},
      {ko:"부정적이다",    uz:"Pessimistik, salbiy fikrlaydigan"},
      {ko:"신중하다",      uz:"Ehtiyotkor, o'ylab ish qiladigan"},
      {ko:"용감하다",      uz:"Jasur, mard, qo'rqmaydigan"},
      {ko:"겸손하다",      uz:"Kamtar, tavozeli"},
      {ko:"이기적이다",    uz:"Xudbinlik, faqat o'zini o'ylaydigan"},
      {ko:"솔직하다",      uz:"Ochiq ko'ngil, to'g'riso'z"},
      {ko:"감동받다",      uz:"Ta'sirlanmoq, ko'ngli to'lmoq"},
      {ko:"실망하다",      uz:"Umidini yo'qotmoq, xafalanmoq"},
      {ko:"후회하다",      uz:"Pushaymon bo'lmoq, afsus qilmoq"},
      {ko:"걱정하다",      uz:"Tashvishlanmoq, xavotirlanmoq"},
    ]
  },
  {
    id:"v2",
    title:"부사·접속어 (Ravishlar & bog'lovchilar)",
    words:[
      {ko:"마침",    uz:"Aynan kerak bo'lgan paytda, o'rinli tarzda"},
      {ko:"드디어",  uz:"Nihoyat — uzoq kutilgan natija yuz berdi"},
      {ko:"겨우",    uz:"Zo'rg'a, qiyinchilik bilan"},
      {ko:"갑자기",  uz:"Birdan, kutilmaganda"},
      {ko:"결국",    uz:"Oxir-oqibat, natijada (ko'pincha salbiy)"},
      {ko:"반드시",  uz:"Albatta, qat'iy ravishda"},
      {ko:"아직",    uz:"Hali (harakat tugamagan yoki davom etayotgan)"},
      {ko:"이미",    uz:"Allaqachon, belgilangan vaqtdan oldin"},
      {ko:"별로",    uz:"Unchalik emas (salbiy gap bilan ishlatiladi)"},
      {ko:"특히",    uz:"Ayniqsa, xususan"},
      {ko:"주로",    uz:"Asosan, ko'pincha"},
      {ko:"점점",    uz:"Asta-sekin, tobora (o'sib yoki kamayib boruvchi)"},
      {ko:"꾸준히",  uz:"Izchil, muntazam ravishda"},
      {ko:"자꾸",    uz:"Qayta-qayta, bo'lmasa ham doim"},
      {ko:"제때",    uz:"O'z vaqtida, kechiktirmasdan"},
      {ko:"오히려",  uz:"Aksincha, buning o'rniga (kutilmagan holat)"},
      {ko:"게다가",  uz:"Bundan tashqari, ustiga ustak"},
      {ko:"전혀",    uz:"Umuman emas (salbiy gap bilan)"},
      {ko:"역시",    uz:"Taxmin qilgandek, albatta ham (xuddi shunday)"},
      {ko:"거의",    uz:"Deyarli, sal qoldi"},
      {ko:"우선",    uz:"Avvalo, birinchi navbatda"},
      {ko:"따라서",  uz:"Shuning uchun, binobarin"},
      {ko:"그러나",  uz:"Lekin, ammo (qarama-qarshi fikr)"},
      {ko:"비록",    uz:"Garchi (... bo'lsa ham)"},
      {ko:"만약",    uz:"Agar, faraz qilsak"},
    ]
  },
  {
    id:"v3",
    title:"직장·행정 어휘 (Ish & ma'muriyat)",
    words:[
      {ko:"승진",              uz:"Lavozim ko'tarilishi, yuqori pog'onaga chiqish"},
      {ko:"이직",              uz:"Boshqa ish joyiga o'tish"},
      {ko:"해고",              uz:"Majburiy ishdan bo'shatish"},
      {ko:"사직",              uz:"O'z xohishi bilan ishdan ketish"},
      {ko:"채용",              uz:"Ishga qabul qilish"},
      {ko:"면접",              uz:"Ish suhbati, intervyu"},
      {ko:"이력서",            uz:"Rezyume, tarjimai hol"},
      {ko:"최저임금",          uz:"Minimal ish haqi (qonuniy pastki chegara)"},
      {ko:"연차",              uz:"Yillik to'liq maoshli ta'til"},
      {ko:"야근",              uz:"Ish vaqtidan tashqari (kechqurun) ishlash"},
      {ko:"정규직",            uz:"Doimiy (kafolatlangan) xodim"},
      {ko:"비정규직",          uz:"Muddatli yoki vaqtinchalik xodim"},
      {ko:"근로계약서",        uz:"Mehnat shartnomasi"},
      {ko:"처방전",            uz:"Retsept — shifokorning yozgan dori ro'yxati"},
      {ko:"발급",              uz:"Hujjat chiqarish (guvohnoma, ko'chirma)"},
      {ko:"신청",              uz:"Ariza berish, murojaat qilish"},
      {ko:"접수",              uz:"Hujjatni qabul qilish, ro'yxatdan o'tkazish"},
      {ko:"등록",              uz:"Ro'yxatdan o'tish, qayd etish"},
      {ko:"신고",              uz:"Rasmiy xabar berish (militsiya, soliq va h.)"},
      {ko:"체류",              uz:"Mamlakat ichida ma'lum muddatga qolib yashash"},
      {ko:"영주권",            uz:"Doimiy yashash huquqi (permanent residence)"},
      {ko:"귀화",              uz:"Fuqarolikka o'tish, naturalizatsiya"},
      {ko:"외국인등록증",      uz:"Chet ellik ro'yxatdan o'tish guvohnomasi (ARC)"},
      {ko:"주민센터",          uz:"Mahalla xizmat markazi (hujjat, ariza uchun)"},
      {ko:"출입국관리사무소",  uz:"Immigratsiya boshqarmasi (viza, ruxsat)"},
    ]
  },
  {
    id:"v4",
    title:"건강·생활 어휘 (Sog'liq & kundalik hayot)",
    words:[
      {ko:"증상",      uz:"Kasallik alomati, simptom"},
      {ko:"치료",      uz:"Davolash, muolaja qilish"},
      {ko:"검진",      uz:"Profilaktik tibbiy tekshiruv"},
      {ko:"악화되다",  uz:"Yomonlashmoq, og'irlashmoq"},
      {ko:"회복하다",  uz:"Tuzalmoq, o'ziga kelmoq"},
      {ko:"예방하다",  uz:"Oldini olmoq, profilaktika qilmoq"},
      {ko:"보람",      uz:"Sayi-harakatga arzigulik his, mehnat samarasi"},
      {ko:"책임감",    uz:"Mas'uliyat hissi"},
      {ko:"여유",      uz:"Bo'sh vaqt, xotirjamlik, imkoniyat"},
      {ko:"우선시하다",uz:"Ustunlik bermoq, birinchi o'ringa qo'ymoq"},
      {ko:"격차",      uz:"Tafovut, farq (ijtimoiy yoki iqtisodiy)"},
      {ko:"수준",      uz:"Daraja, ko'rsatkich, level"},
      {ko:"기준",      uz:"Mezon, standart, o'lchov"},
      {ko:"해결하다",  uz:"Hal qilmoq, muammoni bartaraf etmoq"},
      {ko:"포기하다",  uz:"Voz kechmoq, rad etmoq"},
      {ko:"극복하다",  uz:"Yengmoq, ustidan chiqmoq (to'siq, qiyinlik)"},
      {ko:"도전하다",  uz:"Qiyinchiliqqa dadil yuzlanmoq, challenge"},
      {ko:"발전하다",  uz:"Rivojlanmoq, yuksalmoq"},
      {ko:"유지하다",  uz:"Saqlash, ushlab turmoq"},
      {ko:"실천하다",  uz:"Amalda bajarmoq, hayotga tadbiq etmoq"},
      {ko:"발생하다",  uz:"Yuz bermoq, sodir bo'lmoq"},
      {ko:"결정하다",  uz:"Qaror qilmoq"},
      {ko:"노력하다",  uz:"Harakat qilmoq, intilmoq, tirişmoq"},
      {ko:"경험하다",  uz:"Tajriba olmoq, boshdan kechirmoq"},
      {ko:"이해하다",  uz:"Tushunmoq, anglamoq"},
    ]
  }
];
